FROM ubuntu:latest
#FROM nvidia/cuda:11.0-base

ENV TZ Asia/Seoul
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN apt-get update && apt-get install -y gnupg ca-certificates && \
    apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF && \
    echo "deb https://download.mono-project.com/repo/ubuntu stable-focal main" | tee /etc/apt/sources.list.d/mono-official-stable.list && \
    apt-get update && \
    apt-get install -y mono-complete
# above is for the installation of mono-complete for ubuntu 20.04

RUN apt-get install -y git vim wget

RUN apt-get install -y cmake g++ nvidia-cuda-toolkit

#RUN apt-get install -y xauth wine && \
#    dpkg --add-architecture i386 && apt-get update && apt-get install -y wine32

#RUN mkdir dotnetRoot && \
#    wget https://download.visualstudio.microsoft.com/download/pr/ede8a287-3d61-4988-a356-32ff9129079e/bdb47b6b510ed0c4f0b132f7f4ad9d5a/dotnet-sdk-6.0.101-linux-x64.tar.gz -O /dotnetRoot/dotnet-6.0.tar.gz && \
#    cd /dotnetRoot && \
#    tar xvfz dotnet-6.0.tar.gz

#ENV PATH $PATH:/dotnetRoot

ENV DEBIAN_FRONTEND noninteractive

RUN apt-get install -y software-properties-common && \
    wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/cuda-ubuntu1804.pin && \
    mv cuda-ubuntu1804.pin /etc/apt/preferences.d/cuda-repository-pin-600 && \
    apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/7fa2af80.pub && \
    add-apt-repository "deb https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/ /" && \
    apt-get update && apt-get -y install cuda

ENV PATH $PATH:/usr/local/cuda-11.6/bin
ENV CUDA_PATH /usr/local/cuda-11.6/bin

RUN mkdir warpRoot && cd /warpRoot/ && \
    git clone https://github.com/dtegunov/liblion.git && \
    git clone https://github.com/dtegunov/gtom.git && \
    git clone https://github.com/cramerlab/warp.git

RUN rm /warpRoot/gtom/CMakeLists.txt
COPY ./setupGUI.sh ./home/
COPY ./gtom_modified_CMakeLists.txt /warpRoot/gtom
RUN mv /warpRoot/gtom/gtom_modified_CMakeLists.txt /warpRoot/gtom/CMakeLists.txt && \
    mkdir /warpRoot/gtom/build && \
    cd /warpRoot/gtom/build && \
    cmake .. && \
    make

ENTRYPOINT ["bash", "./home/setupGUI.sh"]
